import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/locale_provider.dart';

/// Lightweight bilingual (English / Bangla) string lookup.
/// Usage: AppStrings.t(context, 'dashboard')
class AppStrings {
  AppStrings._();

  static const Map<String, String> _en = {
    'app_name': 'ABS Hisab Manager',
    'dashboard': 'Dashboard',
    'students': 'Students',
    'transactions': 'Transactions',
    'settings': 'Settings',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'net_balance': 'Net Balance',
    'income': 'Income',
    'expense': 'Expense',
    'total_income': 'Total Income',
    'total_expense': 'Total Expense',
    'pending_fees': 'Pending Fees',
    'net_profit_loss': 'Net Profit / Loss',
    'recent_transactions': 'Recent Transactions',
    'see_all': 'See all',
    'search_students': 'Search students by name, roll...',
    'all': 'All',
    'class_label': 'Class',
    'no_students_yet': 'No students yet',
    'tap_add_student': 'Tap + to add your first student',
    'add_student': 'Add Student',
    'edit_student': 'Edit Student',
    'roll': 'Roll',
    'section': 'Section',
    'monthly_fee': 'Monthly Fee',
    'fathers_name': "Father's Name",
    'fathers_mobile': "Father's Mobile",
    'address': 'Address',
    'admission_date': 'Admission Date',
    'notes_optional': 'Notes (optional)',
    'save_student': 'Save Student',
    'update_student': 'Update Student',
    'call_father': 'Call Father',
    'message': 'Message',
    'send_due_sms': 'Send Due Reminder SMS',
    'no_due_msg': 'Student has no pending due!',
    'no_phone_msg': 'Father mobile number is empty!',
    'statement_pdf': 'Statement PDF',
    'class_attendance': 'Class Attendance',
    'classes': 'classes',
    'collect_payment': 'Collect Payment',
    'current_due': 'Current Due',
    'amount': 'Amount',
    'payment_method': 'Payment Method',
    'payment_date': 'Payment Date',
    'month_hint': 'Month (e.g. 2025-01)',
    'note_optional': 'Note (optional)',
    'give_receipt_now': 'Give money receipt now?',
    'receipt_now_desc': 'Receipt will be shown/printed immediately',
    'save_payment_generate_receipt': 'Save Payment & Generate Receipt',
    'total_expected': 'Total Expected',
    'total_paid': 'Total Paid',
    'due': 'Due',
    'advance': 'Advance',
    'payment_history': 'Payment History',
    'receipt_given': 'Receipt given',
    'no_receipt': 'No receipt',
    'no_payments_yet': 'No payments yet',
    'report': 'Report',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    'language': 'Language',
    'bangla': 'বাংলা',
    'english': 'English',
    'print_share': 'Print / Share',
    'cash': 'Cash',
    'bkash': 'bKash',
    'nagad': 'Nagad',
    'rocket': 'Rocket',
    'classes_nav': 'Classes',
    'manage_classes': 'Manage Classes & Subjects',
    'add_class': 'Add Class',
    'edit_class': 'Edit Class',
    'class_name': 'Class Name',
    'sections': 'Sections',
    'subjects': 'Subjects',
    'total_income_month': 'Total Income',
    'total_expense_month': 'Total Expense',
    'guardian_name': 'Guardian Name',
    'guardian_phone': 'Guardian Phone Number',
    'student_phone': "Student's Own Phone Number (Optional)",
    'direct_communication': 'Direct Communication',
    'call': 'Call',
    'sms': 'SMS',
    'whatsapp': 'WhatsApp',
    'telegram': 'Telegram',
    'save_contact': 'Save',
    'delete_payment': 'Delete Payment',
    'delete_payment_confirm':
        'This will permanently remove this payment record. Continue?',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'quick_actions': 'Quick Actions',
    'quick_collect_fee': 'Collect Fee',
    'quick_add_student': 'Add Student',
    'quick_add_expense': 'Add Expense',
    'quick_reports': 'Reports',
    'select_student': 'Select Student',
    'filter_all': 'All',
    'filter_due': 'With Due',
    'filter_paid': 'Paid',
    'filter_advance': 'Advance',
    'expense_breakdown': 'Expense Breakdown',
    'no_expenses_recorded': 'No expenses recorded yet',
    'no_transactions_yet': 'No transactions yet. Tap + to add one.',
    'security': 'Security',
    'finance': 'Finance',
    'data_backup': 'Data & Backup',
    'about': 'About',
  };

  static const Map<String, String> _bn = {
    'app_name': 'ABS হিসাব ম্যানেজার',
    'dashboard': 'ড্যাশবোর্ড',
    'students': 'শিক্ষার্থী',
    'transactions': 'লেনদেন',
    'settings': 'সেটিংস',
    'good_morning': 'শুভ সকাল',
    'good_afternoon': 'শুভ দুপুর',
    'good_evening': 'শুভ সন্ধ্যা',
    'net_balance': 'নিট ব্যালেন্স',
    'income': 'আয়',
    'expense': 'ব্যয়',
    'total_income': 'মোট আয়',
    'total_expense': 'মোট ব্যয়',
    'pending_fees': 'বাকি ফি',
    'net_profit_loss': 'নিট লাভ/ক্ষতি',
    'recent_transactions': 'সাম্প্রতিক লেনদেন',
    'see_all': 'সব দেখুন',
    'search_students': 'নাম, রোল দিয়ে খুঁজুন...',
    'all': 'সব',
    'class_label': 'শ্রেণি',
    'no_students_yet': 'এখনো কোনো শিক্ষার্থী নেই',
    'tap_add_student': 'প্রথম শিক্ষার্থী যুক্ত করতে + চাপুন',
    'add_student': 'শিক্ষার্থী যুক্ত করুন',
    'edit_student': 'শিক্ষার্থী সম্পাদনা',
    'roll': 'রোল',
    'section': 'শাখা',
    'monthly_fee': 'মাসিক ফি',
    'fathers_name': "পিতার নাম",
    'fathers_mobile': "পিতার মোবাইল",
    'address': 'ঠিকানা',
    'admission_date': 'ভর্তির তারিখ',
    'notes_optional': 'নোট (ঐচ্ছিক)',
    'save_student': 'শিক্ষার্থী সংরক্ষণ করুন',
    'update_student': 'তথ্য আপডেট করুন',
    'call_father': 'পিতার সাথে কল',
    'message': 'মেসেজ',
    'send_due_sms': 'বকেয়া রিমাইন্ডার SMS',
    'no_due_msg': 'শিক্ষার্থীর কোনো বকেয়া ফি নেই!',
    'no_phone_msg': 'পিতার মোবাইল নম্বর দেওয়া হয়নি!',
    'statement_pdf': 'স্টেটমেন্ট PDF',
    'class_attendance': 'ক্লাস উপস্থিতি',
    'classes': 'ক্লাস',
    'collect_payment': 'পেমেন্ট সংগ্রহ',
    'current_due': 'বর্তমান বাকি',
    'amount': 'পরিমাণ',
    'payment_method': 'পেমেন্ট পদ্ধতি',
    'payment_date': 'পেমেন্টের তারিখ',
    'month_hint': 'মাস (যেমন 2025-01)',
    'note_optional': 'নোট (ঐচ্ছিক)',
    'give_receipt_now': 'এখন রশিদ দিবেন?',
    'receipt_now_desc': 'রশিদ তৎক্ষণাৎ দেখানো/প্রিন্ট হবে',
    'save_payment_generate_receipt': 'পেমেন্ট সেভ করুন ও রশিদ তৈরি করুন',
    'total_expected': 'মোট প্রত্যাশিত',
    'total_paid': 'মোট পরিশোধিত',
    'due': 'বাকি',
    'advance': 'অগ্রিম',
    'payment_history': 'পেমেন্ট ইতিহাস',
    'receipt_given': 'রশিদ দেওয়া হয়েছে',
    'no_receipt': 'রশিদ দেওয়া হয়নি',
    'no_payments_yet': 'এখনো কোনো পেমেন্ট রেকর্ড নেই',
    'report': 'রিপোর্ট',
    'daily': 'দৈনিক',
    'weekly': 'সাপ্তাহিক',
    'monthly': 'মাসিক',
    'yearly': 'বার্ষিক',
    'language': 'ভাষা',
    'bangla': 'বাংলা',
    'english': 'English',
    'print_share': 'প্রিন্ট / শেয়ার',
    'cash': 'ক্যাশ',
    'bkash': 'বিকাশ',
    'nagad': 'নগদ',
    'rocket': 'রকেট',
    'classes_nav': 'শ্রেণি/ব্যাচ',
    'manage_classes': 'শ্রেণি ও বিষয় ব্যবস্থাপনা',
    'add_class': 'নতুন শ্রেণি যোগ',
    'edit_class': 'শ্রেণি সম্পাদনা',
    'class_name': 'শ্রেণির নাম',
    'sections': 'শাখা (Sections)',
    'subjects': 'বিষয়সমূহ (Subjects)',
    'total_income_month': 'মোট আয়',
    'total_expense_month': 'মোট ব্যয়',
    'guardian_name': 'অভিভাবকের নাম',
    'guardian_phone': 'অভিভাবকের মোবাইল নম্বর',
    'student_phone': 'শিক্ষার্থীর নিজস্ব মোবাইল (ঐচ্ছিক)',
    'direct_communication': 'Direct Communication',
    'call': 'Call',
    'sms': 'SMS',
    'whatsapp': 'WhatsApp',
    'telegram': 'Telegram',
    'save_contact': 'Save',
    'delete_payment': 'পেমেন্ট মুছুন',
    'delete_payment_confirm':
        'এই পেমেন্ট রেকর্ডটি স্থায়ীভাবে মুছে যাবে। এগিয়ে যাবেন?',
    'cancel': 'বাতিল',
    'delete': 'মুছুন',
    'quick_actions': 'কুইক অ্যাকশন',
    'quick_collect_fee': 'ফি গ্রহণ',
    'quick_add_student': 'শিক্ষার্থী যোগ',
    'quick_add_expense': 'ব্যয় যোগ',
    'quick_reports': 'রিপোর্টস',
    'select_student': 'শিক্ষার্থী নির্বাচন করুন',
    'filter_all': 'সব',
    'filter_due': 'বকেয়া আছে',
    'filter_paid': 'পরিশোধিত',
    'filter_advance': 'অগ্রিম',
    'expense_breakdown': 'ব্যয়ের বিবরণী',
    'no_expenses_recorded': 'কোনো ব্যয় রেকর্ড করা হয়নি',
    'no_transactions_yet': 'কোনো লেনদেন নেই। + চাপুন।',
    'security': 'নিরাপত্তা',
    'finance': 'আর্থিক হিসাব',
    'data_backup': 'ডাটা ও ব্যাকআপ',
    'about': 'সম্পর্কে',
  };

  static String t(BuildContext context, String key) {
    final isBn = context.watch<LocaleProvider>().isBangla;
    final map = isBn ? _bn : _en;
    return map[key] ?? _en[key] ?? key;
  }

  /// Non-listening variant for use inside build methods where a watch()
  /// higher up already triggers rebuilds (e.g. PDF generation, one-off).
  static String tr(BuildContext context, String key) {
    final isBn = context.read<LocaleProvider>().isBangla;
    final map = isBn ? _bn : _en;
    return map[key] ?? _en[key] ?? key;
  }
}
